### ISSUE TITLE
Creating the package

### ISSUE THREAD

**Issue by Betanu701** [ismarslomic/google-assistant-broadcast#1]
This is great work!

To make it easier on others who may want to use this. You can create your docker file and package it up and push it directly to github. This will allow people to point directly to the packages without needing to know how to use docker commands for building.

Let me know if you want help.

**Comment by ismarslomic** [comment]
Thanks @Betanu701!
Not sure if I'm following you, could you explain a bit more or create PR?

**Comment by Betanu701** [comment]
I now understand why you were confused. I actually made a mistake. You do have the package published. 

Sorry for the inconvenience! Keep up the good work
