### ISSUE TITLE
Add support for sending commands to Google Assistant

### ISSUE THREAD

**Issue by Trilis29** [ismarslomic/google-assistant-broadcast#10]
Could you allow to send commands instead of broadcast.  So I could turn on some routines or send commands to assistant?

**Comment by maxi1134** [comment]
This would be very appreciated!

**Comment by tjkcc** [comment]
+1

**Comment by Trilis29** [comment]
Mainly the reason would be to use broadcast command from google routines, so after automation normal voice could say "Dishwasher finished". Without all this "broadcasting ...."

**Comment by flecmart** [comment]
This is a thing I would also appreciate... As a way to trigger google home routines from home assistant 👍 

Maybe I can also contribute a PR if I find some time... from researching a bit in previous projects I think commands can just be send to by omitting the `Broadcast` in https://github.com/ismarslomic/google-assistant-broadcast/blob/4b29492010dce55a1be22d7dd3146998a2278bc6/assistant.js#L72

So there could be 2 endpoints one for broadcasts and one for generic text commands.

**Comment by tjkcc** [comment]
> This is a thing I would also appreciate... As a way to trigger google home routines from home assistant 👍
> 
> Maybe I can also contribute a PR if I find some time... from researching a bit in previous projects I think commands can just be send to by omitting the `Broadcast` in
> 
> https://github.com/ismarslomic/google-assistant-broadcast/blob/4b29492010dce55a1be22d7dd3146998a2278bc6/assistant.js#L72
> 
> So there could be 2 endpoints one for broadcasts and one for generic text commands.

There are other solutions for sending commands instead of broadcasts from HA to Google, but keep in mind that you won't be able to trigger the built-in Home/Away routines. Doesn't work. The rest of the routines you can.

**Comment by Trilis29** [comment]
> > This is a thing I would also appreciate... As a way to trigger google home routines from home assistant 👍
> > Maybe I can also contribute a PR if I find some time... from researching a bit in previous projects I think commands can just be send to by omitting the `Broadcast` in
> > https://github.com/ismarslomic/google-assistant-broadcast/blob/4b29492010dce55a1be22d7dd3146998a2278bc6/assistant.js#L72
> > 
> > So there could be 2 endpoints one for broadcasts and one for generic text commands.
> 
> There are other solutions for sending commands instead of broadcasts from HA to Google, but keep in mind that you won't be able to trigger the built-in Home/Away routines. Doesn't work. The rest of the routines you can.

What ways do you suggest?
My intension is to make routine for example: When I say dishwasher finished, announce to household "Take fkcin dishes out" 

So I can have great nice google assistant voice instead of google translate robotic tts. 

Home Assistant would trigger command or routine and that would be perfect.

**Comment by flecmart** [comment]
> > > This is a thing I would also appreciate... As a way to trigger google home routines from home assistant 👍
> > > Maybe I can also contribute a PR if I find some time... from researching a bit in previous projects I think commands can just be send to by omitting the `Broadcast` in
> > > https://github.com/ismarslomic/google-assistant-broadcast/blob/4b29492010dce55a1be22d7dd3146998a2278bc6/assistant.js#L72
> > > 
> > > So there could be 2 endpoints one for broadcasts and one for generic text commands.
> > 
> > 
> > There are other solutions for sending commands instead of broadcasts from HA to Google, but keep in mind that you won't be able to trigger the built-in Home/Away routines. Doesn't work. The rest of the routines you can.
> 
> What ways do you suggest? My intension is to make routine for example: When I say dishwasher finished, announce to household "Take fkcin dishes out"
> 
> So I can have great nice google assistant voice instead of google translate robotic tts.
> 
> Home Assistant would trigger command or routine and that would be perfect.

yes I would like to use it in a similar way. I already forked the repo and implemented it but I could not test it unfortunately because I am not able to complete the auth workflow... I opened an issue #11 for this... all in all integrating this was frustrating so I stopped for now.

**Comment by ismarslomic** [comment]
Thanks for opening this feature request, but this topic has already been answered in #2. I don't want to increase the complexity of the solution, as it is already challenging to do the debugging with broadcast alone (ref #11, #5 and #9). Closing the issue.

**Comment by codahq** [comment]
@ismarslomic you should consider re-opening this.  you have said in the HA community forums and in issues in github you can't broadcast to individual devices but you can.  in greg's original solution (assistant relay) if you set broadcast to false and converse to false (so that a command would be sent) so that you passed something like this:

{"user":"{{yourvaliduser}}","command":"broadcast to office hello, this is a test message."}

it will send to just the speaker(s) in the room "office".  This was functionality Google introduced a year or two ago.  However, it only works when the message is sent as a command.

This works so reliably that on another home automation platform I could create virtual individual speakers and then make a virtual speaker send the command "broadcast to {{the_provided_speaker_room_name}} {{original_message}}".  I have been broadcasting to individual speakers for almost a year.

I have finally cutover the rest of my devices to HA though so I can no longer use the solution from the other home automation platform.  I am hoping you can allow this functionality here so I can continue to broadcast to individual speakers now that I've moved over completely to HA.

**Comment by ismarslomic** [comment]
Interesting, I was not aware of that you need to send the broadcast as a command to get it work with specific speaker. Thanks for the heads up. 

I can give it a shot and see how it works!

**Comment by ismarslomic** [comment]
I have added a way to opt out the prefix of `broadcast` in the message, so you can basically send whatever you want to Google Assistant. I tested it quickly at home and I where able to switch off/on my lights, but I haven't done any extensive tests of other Assistant use cases. 

I did also manage to send `broadcast to living room, Hello world` message, and it played the message `Hello world` on my speaker, but I only got one speaker at home, so I where not able to test if this really works when having more then one speaker.

Can anyone with multiple speakers test the command and directing to specific speaker feature?

Use following image: `ismarslomic/google-assistant-broadcast:main` and add `APPEND_BROADCAST_TO_MESSAGE=false` to env variables in your `docker run` command / `docker-compose` file.

See also updated [README](https://github.com/ismarslomic/google-assistant-broadcast#broadcasting-to-all-or-specific-speaker) doc

**Comment by maxi1134** [comment]
Just updated, Commands and single-speaker broadcast work for me.

**Comment by Trilis29** [comment]
Commands works, but  does it work for routines for you? I have tried to enable routine with command not working

**Comment by ismarslomic** [comment]
> Just updated, Commands and single-speaker broadcast work for me.

Nice! For me it worked sending message to specific speaker when writing in english, but not in Norwegian. I think I did read somewhere that broadcasting to specific speaker was not supported in all languages

**Comment by ismarslomic** [comment]
> Commands works, but does it work for routines for you? I have tried to enable routine with command not working

I haven't tested, as I only use HA for automation. I think Assistant routines has poor user experience and don't see any benefit using it when I got HA

**Comment by Trilis29** [comment]
> 

I need routines just for only 1 purpose. Announce message. 
For example making routine: when I say dishwasher done > announce: “Dishwasher has finished, please take out the dishes”

Then you won’t hear any intro like Broadcasting… just straight non robotic words. This would be best feature to integrate response on speakers in automations.

**Comment by maxi1134** [comment]
As far as I understand there is a few things that the command APi on google cannot do.

Amongst those; Routines and starting music.

I will try to find a source later!

**Comment by ismarslomic** [comment]
I see, well. I'm not sure why routine commands doesn't work as I dont use Google Assistant for those use cases (thus reason why I wanted to keep this solution as narrowed and simple as possible). But feel free to explore it and see if you can manage to get it work.

Personally, I would place a [Flic](https://flic.io) button just beside the dishwasher and press it manually, so it triggers an HA automation (via webhook), which uses this broadcast solution to make an announcement.

Closing this issue as support for commands has been provided.

**Comment by Trilis29** [comment]
> 

I have that solution, but I really hate this "Broadcast incoming...." I would like ONLY the phrase Dishwasher finished
