### ISSUE TITLE
dumb-init: Permission denied

### ISSUE THREAD

**Issue by mortimus1987** [ismarslomic/google-assistant-broadcast#3]
Using the arm/v7 container in docker on raspberry pi3
Container exits with the following message:

ash: can't open '/usr/local/bin/dumb-init': Permission denied

Could just be a permissioning error, but it may also be related to the use of the x86 release of dumb-init.

**Comment by ismarslomic** [comment]
@mortimus1987 thanks for reporting this bug. I have changed the way we install dumb-init and tested successfully on my RPI4. Can you please pull `latest` version (or `v1.0.3`) of the Docker Image and verify that the issue is resolved?

**Comment by mortimus1987** [comment]
That seems to have fixed this error, as the container now starts successfuly. Docker logs command now reports:

`Google Assistant Broadcast started at: http://localhost:8085`

But when I attempt to call the api with curl, I get a response of:

`{"error":{}}`

which is not terribly informative. However, I think this particular issue is solved. I'll try and investigate the new one and report back.

**Comment by ismarslomic** [comment]
Ok. Please create new issue and describe steps to reproduce the issue you are facing.

I tried following curl request on my RPI4:
`curl -X POST http://localhost:8085/broadcast  -d '{"message":"Hello world!!"}'  -H "Content-Type: application/json"`

and see following ouput in docker log:
```
Google Assistant Broadcast started at: http://localhost:8085
Sending message: Broadcast Hello world!!
[OK] Conversation Response:  empty
[OK] Conversation Completed
```
