### ISSUE TITLE
Getting error as response when broadcasting a message

### ISSUE THREAD

**Issue by chrisjenx** [ismarslomic/google-assistant-broadcast#7]
Hey thanks for putting this together, unforutnatly after getting the token and client_secrete when sending curl commands to the docker container all I get is error outputs:

Checked Google API console, no requests ever hit it, so looks like an issue before it even gets that far, fyi I'm running docker on x86 machines, not sure if that makes a difference considering it's node?

![image](https://user-images.githubusercontent.com/1167793/172763598-2d81f5de-99a1-46ac-967a-9a7040f69f5f.png)

**Comment by chrisjenx** [comment]
I was trying to run the server locally to debug but node dosn't want to play ball, I think I got node to work once in my life:

```
{"error":{"code":"MODULE_NOT_FOUND","requireStack":["/Users/chrisjenkins/git/google-assistant-broadcast/node_modules/google-assistant/components/auth.js","/Users/chrisjenkins/git/google-assistant-broadcast/node_modules/google-assistant/index.js","/Users/chrisjenkins/git/google-assistant-broadcast/assistant.js","/Users/chrisjenkins/git/google-assistant-broadcast/index.js"]}}%
```

Followed all google steps for cleaning/reinstall 🤷

**Comment by ismarslomic** [comment]
The error handling and error messages are currently not quite useful. Will take a look at it!

However, what node is trying to tell you is that it fails importing client secret and tokens file.

You can set path to these two files by starting node with env vars mentioned in line 8 and 12 in [assistant.js](https://github.com/ismarslomic/google-assistant-broadcast/blob/main/assistant.js)

**Comment by chrisjenx** [comment]
The docker container can see and access these files as I can cd and cat the
files inside the container. So I'm a little confused. Maybe I fat fingered
a name...

**Comment by chrisjenx** [comment]
OK got it working locally, without a better error in the docker container not sure where to go there. However this got me thinking about https://developers.google.com/assistant/smarthome/develop/notifications#java
I might throw something together to see if works how I think it should

**Comment by ismarslomic** [comment]
You started index.js in Node locally and then it worked?

**Comment by chrisjenx** [comment]
Yeah works locally (I just set the tokens and client secret with full path from root and it worked).

Still no luck on docker, files are readable and accessable inside the docker container and the error is just blank as above. Not sure if theres any better error logging to be had?

**Comment by ismarslomic** [comment]
I did release new version 1.0.5 of Docker image today. I added validation of required files, checking if they exist. You could give it a try? I dont get why Docker should introduce any issues here..

**Comment by chrisjenx** [comment]
Just updated, started up fine, same issue.. no error in logs too, super weird..

➜  ~ curl -X POST http://10.10.106.2:8085/broadcast \
 -d '{"message":"Hello world!!"}' \
 -H "Content-Type: application/json"
{"error":{}}%

**Comment by ismarslomic** [comment]
While doing some testing few minutes ago, I experienced same issue on my side. Everything looked correct, but response where empty error. And I managed to fix it 🥳 . 

Issue where that I downloaded the _OAuth 2.0 credential_ file for my registered device from the [Google Actions Console ](https://console.actions.google.com) and used that to generate the OAuth Token (with use of `google-assistant-oauth` docker container). When I tried to use the `client_secret.json` and `tokens.json`, I received error as response.

<img width="724" alt="google-actions-console" src="https://user-images.githubusercontent.com/2174314/172940063-6ba29c51-c13d-4426-9187-ea7262391947.png">

But, when I used the _OAuth client_ file, downloaded from the [Google Cloud Platform console](https://console.cloud.google.com/apis/credentials), then it worked.

<img width="1068" alt="gcp-console" src="https://user-images.githubusercontent.com/2174314/172940088-b8df3d4c-71d0-45f8-aa2b-90adffd9f0f0.png">

I looked at the content of these two files and the main difference where on two places:

_OAuth 2.0 credential_ file:
```(json)
{
  ...
  "token_uri": "https://accounts.google.com/o/oauth2/token"
}
```

_OAuth client_ file:
```(json)
{
  ...
  "token_uri": "https://oauth2.googleapis.com/token",
  "redirect_uris": [
      "http://localhost"
  ]
}
```

So you could check which of these files you are using, and try to download the one from GCP Console.

**Comment by chrisjenx** [comment]
Yup that missing `"token_uri": "https://accounts.google.com/o/oauth2/token"` fixed it for me instantly, interesting!

Not sure why running locally worked with the files missing those...

**Comment by ismarslomic** [comment]
Nice! Happy to see that you are finally up and running with google-assistant-broadcast docker container!

I have added new validation steps in both docker images, so new folks can easily identify this issue. Thanks for reporting this issue!

Can we close this issue now?

**Comment by chrisjenx** [comment]
Yes thank you!
