### ISSUE TITLE
Token expires

### ISSUE THREAD

**Issue by chrisjenx** [ismarslomic/google-assistant-broadcast#8]
Still looking into it but rebooting docker and now seeing:

```
[2022-06-19T17:53:13.335Z] [ERROR] Error while broadcasting: Error: 16 UNAUTHENTICATED: Failed to retrieve auth metadata with error: invalid_grant
    at Object.callErrorFromStatus (/usr/src/app/node_modules/@grpc/grpc-js/build/src/call.js:31:26)
    at Object.onReceiveStatus (/usr/src/app/node_modules/@grpc/grpc-js/build/src/client.js:391:49)
    at Object.onReceiveStatus (/usr/src/app/node_modules/@grpc/grpc-js/build/src/client-interceptors.js:328:181)
    at /usr/src/app/node_modules/@grpc/grpc-js/build/src/call-stream.js:187:78
    at process.processTicksAndRejections (node:internal/process/task_queues:77:11) {
  code: 16,
  details: 'Failed to retrieve auth metadata with error: invalid_grant',
  metadata: Metadata { internalRepr: Map(0) {}, options: {} }
}
```

**Comment by chrisjenx** [comment]
It's like the cert just randomly invalidated it'self, I'll refresh and redownload and see if it fixes it

**Comment by chrisjenx** [comment]
Seems like redownloading and reauthin to get a new tokens.js fixed it.
Wondering if the container needs to run a periodic refresh token command to make sure it doesn't expire?

**Comment by ismarslomic** [comment]
Glad to hear to you fixed the issue.

I have been running my docker container for couple of weeks without need for any manual refreshing of tokens, or re-downloading the tokens file. So I'm not sure refreshing the token is the issue. 

I suggest that you leave your container running for couple of days/weeks now, when everything is working, and see how it goes.

Closing this issue for now, but please report back if you face any new issues!

**Comment by chrisjenx** [comment]
Looks like 11 days later and same error, wondering if my generated token has a short ttl

**Comment by chrisjenx** [comment]
So yeah 7 days, looks like this is how oauth works on testing accounts.

> Refresh tokens will actually expire after 7 days if the project publishing status is "testing". Per google documentation: A Google Cloud Platform project with an OAuth consent screen configured for an external user type and a publishing status of "Testing" is issued a refresh token expiring in 7 days.

**Comment by chrisjenx** [comment]
If you look inside your `tokens.json` you'll see your bearer expires: 

`"token_type":"Bearer","expiry_date":1657083576057}`

**Comment by chrisjenx** [comment]
I'm guessing your either have a published project? or you have managed to set a longer token somehow

**Comment by chrisjenx** [comment]
Oh you need to publish the app: https://stackoverflow.com/a/67367752/803225

**Comment by chrisjenx** [comment]
yeah Ive published my app and refreshed the token, lets see if it lasts more than 7 days

**Comment by ismarslomic** [comment]
Thanks for the input! I have re-opened this issue. 

I have not published my app in Google Assistant Console, so I dont think that is required in order to fix the token refreshing. And, Im still using the same token I generated months ago without any issues. What I assume is different between mine and yours setup is that Im using the Google Assistant broadcast every day in HA automation and I think that token is automatically refreshed when actively using the broadcast API and underlaying lib https://github.com/endoplasmic/google-assistant.

But it is also possible to schedule token refreshes, to avoid need for frequent usage of the broadcast api!

Im currently on vaccation, but will look at this in couple of weeks or so. 

Help and PR is of course welcome!

**Comment by chrisjenx** [comment]
Maybe, but we send a Broadcast at least once a day, I noticed where it sent one in the morning and didn't later (When the garage was left open).

I'm wondering if there is some nuanced way the projects are setup/tokens, or that my setup is not able to refresh the token and write it to disk (maybe my docker container config?)

**Comment by ismarslomic** [comment]
Oh, then my assumption might be incorrect.

Another solution would be to publish the google assistant broadcast as custom HA component and let HA take care of OAuth flow (authentication and refreshing). But that requires development that I dont have time for currently.

**Comment by chrisjenx** [comment]
Maybe, let's see what happens in a week. 
I really would like NabuCasa to add notification intergration into the cloud sub (https://developers.google.com/assistant/smarthome/develop/notifications) that would make that much more useful, where a doorbell could just send a direct notification instead of a roundabout Broadcast.

I started going down that route, but you need to create/register devices, which is possible as a HA plugin as they already expose those devices to Google Assistant - I was trying to do a standalone docker image.

**Comment by chrisjenx** [comment]
Seems publishing my project fixed it, 20+ days on still working!

**Comment by ismarslomic** [comment]
Thanks for the update, and happy to see that this solved your issue! So basically what you did where to configure the OAuth Consent Screen for your app in the Google Console?

**Comment by chrisjenx** [comment]
Yeah on this screen: 

![image](https://user-images.githubusercontent.com/1167793/183966034-f614af5f-1055-4e24-b075-cb4b4baa2ee3.png)

https://console.cloud.google.com/apis/credentials/consent

**Comment by chrisjenx** [comment]
Little confused why yours is fine without being published, but seems to fix it for me 🤷

**Comment by ismarslomic** [comment]
Alright! Glad you fixed the issue and I hope you are enjoying the Google Broadcast 👍

**Comment by chrisjenx** [comment]
Thank you, appreciate it!
